defaults:
  - _self_

simulation:
  rounds: 20 
  n_clients: 40
  fraction: 1.0
  partition_method: "iid"
  alpha: 0.5

client:
  epochs: 1    #10
  lr: 0.01
  batch_size: 32
  device: "cuda"  # Change to "cuda" if you have GPU

server:
  defense: "krum"   # "avg", "median", "trimmed_mean", "krum"
                    # if you use "krum" --> update the # of malicious clients in server.py, default value = 1

data:
  path: "data/unsw-nb15/processed/train_pool.pt"

#ðŸ˜ˆ RED TEAM SECTION
attack:
  type: "backdoor"   # Options: clean, backdoor, label_flip
  poison_ratio: 0.3
  trigger_feat_idx: 0
  trigger_value: 5.0
  target_label: 0
  source_label: 3    # Only used for label_flip
  flip_to_label: 0   # Only used for label_flip
