# configs/central/m1_baseline.yaml

name : "Centralized_M1_Baseline_UNSW"
# Data Settings (Points to your UNSW-NB15 processed data)
# NOTE: Ensure this path matches exactly where your .pt files are
train_data_path: "data/cic-unsw-nb15/processed/train_pool.pt"
val_data_path : "data/cic-unsw-nb15/processed/global_test.pt"

# Model Hyperparameters (Matches your Net class)
input_dim: 61
num_classes: 10 
hidden_sizes: [128, 64, 32] # Implicitly defined in your Net class, just for logging info
dropout: 0.2

# Training Settings
batch_size: 128
epochs: 20
lr: 0.001
device: "cuda"

# --- MILESTONE SWITCHES ---
# Milestone 1 is the "Truthful Baseline" (No tricks)
use_class_weights: false

wandb:
  project: "e20-4yp-backdoor-resilient-federated-nids"
  group : "central_m1_mlp_baseline_cic_unsw"
  tags: []        # Will be filled by CLI